### ISSUE TITLE
Configure typesync to lookup on internal repository

### ISSUE THREAD

**Issue by josephstgh** [jeffijoe/typesync#39]
Hi,

I am using Nexus OSS Repository internally to fetch node packages as I am running on offline mode.
When I run `typesync`, it will complain the following:

> getaddrinfo ENOTFOUND typepublisher.blob.core.windows.net typespublisher.blob.core.windows.net:443
Stack:
Error: getaddrinfo ENOTFOUND typepublisher.blob.core.windows.net typespublisher.blob.core.windows.net:443 at GetAddrInfoReqWrap.onLookup [as oncomplete] (dns.js:56:26)

Using `typesync v0.6.1`

Is it possible to set the config somewhere, or use `npm registry` config as a reference point to know where to lookup the packages in?

Thanks.

**Comment by jeffijoe** [comment]
What you mentioned is indeed going to be a problem, but the error you posted is actually occurring a step before that. The `typepublisher` URL is where TypeSync grabs information about available typings, so it won't work in offline mode. 

Since TypeSync does not actually install the packages, using the public npm registry should be fine.

**Comment by josephstgh** [comment]
So it means that TypeSync does not support for offline mode right? Since it needs to fetch data from `typepublisher`.

Hopefully there is someway to support it in the future though.

Thanks!

**Comment by jeffijoe** [comment]
Yes, that’s correct.
