### ISSUE TITLE
Seemingly incorrect @types versions

### ISSUE THREAD

**Issue by devinrhode2** [jeffijoe/typesync#78]
In our package.json, we have dependency:
```
"react": "~16.13.1",
```

Running `yarn why` clearly shows we have `16.13.1` installed.

After running `npx typesync` - I have:

```
"@types/react": "~17.0.24",
```

But... this is very clearly wrong... Unless there's something special I don't understand about react 16->17 types

**Comment by devinrhode2** [comment]
I believe I had deleted all @types packages from package.json before getting this result.

Although, I certainly did still have this package installed inside of my node_modules:
```
"@types/react": "^16.9.48",
```
Could this have had an effect?

**Comment by jeffijoe** [comment]
My best guess is that there is no `16.13` range of the `@types/react` package, and since you are using the `~` range specifier, TypeSync can't [find a version that matches](https://github.com/jeffijoe/typesync/blob/4a012b7b50fee780b3b1d5fbabde06ca1ef7cd09/src/type-syncer.ts#L248), and so it picks the latest available as a fallback.

TypeSync uses the `satisfies` function from the `semver` package for this.

**Comment by devinrhode2** [comment]
I think best thing people can do in similar situation is to just open up npmjs.com/package/@types/FOO and browse the available versions, and hand-pick a package. That, or just install/update them as you go along
